### ISSUE TITLE
lazyLoad causing problems

### ISSUE THREAD

**Issue by maackle** [alpacaaa/purescript-simplecrypto#1]
For some reason `lazyLoad` is causing problems for me, [i.e. here](https://github.com/alpacaaa/purescript-simplecrypto/commit/ea76185396ea488c9d9c53f063d27f828213f0b3#diff-b5c28be71cbd384021f00f69d984da89R4)

Probably related to this: https://github.com/webpack/webpack/issues/4921#issuecomment-342523044

I get the error:

    Uncaught Error: Cannot find module "."

But if I change that line to `const getBasex = () => require("base-x")` it works fine (not sure if it has the same lazy loading behavior though...

Just leaving a note in case anybody else has this problem. I'm probably just going to use a fork for now.

**Comment by alpacaaa** [comment]
Thanks for letting me know! I will look into it and release a new version soon.

**Comment by alpacaaa** [comment]
Version `0.1.0` should be working correctly.
