### ISSUE TITLE
Spago doesn't see neither purescript-simplecrypto  nor purescript-simplecrypto 

### ISSUE THREAD

**Issue by radrow** [alpacaaa/purescript-simplecrypto#5]
```
>>> spago build
[error] The following packages do not exist in your package set:
[error]   - purescript-simplecrypto, and nor does `simplecrypto`
```
I have installed it via bower along with all dependencies via npm. What could be wrong?

**Comment by alpacaaa** [comment]
This package is not in the default spago package-set, so you'll have
to add it manually. Instructions are here:
https://github.com/purescript/spago#add-a-package-to-the-package-set

Bear in mind this is a very old package I haven't updated in a way, so
it might break for other reasons! :)

2020-12-15 14:55 GMT+01:00, Radosław Rowicki <notifications@github.com>:

**Comment by radrow** [comment]
Thanks!
